[tool.poetry]
name = "kgpi"
version = "0.1.0"
description = ""
authors = ["Roman Grigoryev <hjklvfr@list.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

